package com.github.mrwinabagel;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.block.FabricBlockSettings;
import net.fabricmc.fabric.api.tools.FabricToolTags;
import net.minecraft.block.Block;
import net.minecraft.block.Material;
import net.minecraft.item.*;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class compressedblocks implements ModInitializer {

	private static final Block COMPRESSED_COBBLESTONE = new CompressedCobblestone(FabricBlockSettings.of(Material.STONE).strength(3, 40).breakByTool(FabricToolTags.PICKAXES, 0).build());
	private static final Item COMPRESSED_COBBLESTONE_ITEM = new BlockItem(COMPRESSED_COBBLESTONE, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_COBBLESTONE2 = new CompressedCobblestone(FabricBlockSettings.of(Material.STONE).strength(4, 100).breakByTool(FabricToolTags.PICKAXES, 0).build());
	private static final Item COMPRESSED_COBBLESTONE2_ITEM = new BlockItem(COMPRESSED_COBBLESTONE2, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_COBBLESTONE3 = new CompressedCobblestone(FabricBlockSettings.of(Material.STONE).strength(6, 200).breakByTool(FabricToolTags.PICKAXES, 0).build());
	private static final Item COMPRESSED_COBBLESTONE3_ITEM = new BlockItem(COMPRESSED_COBBLESTONE3, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_COBBLESTONE4 = new CompressedCobblestone(FabricBlockSettings.of(Material.STONE).strength(8, 5000).breakByTool(FabricToolTags.PICKAXES, 0).build());
	private static final Item COMPRESSED_COBBLESTONE4_ITEM = new BlockItem(COMPRESSED_COBBLESTONE4, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_COBBLESTONE5 = new CompressedCobblestone(FabricBlockSettings.of(Material.STONE).strength(10, 10000).breakByTool(FabricToolTags.PICKAXES, 0).build());
	private static final Item COMPRESSED_COBBLESTONE5_ITEM = new BlockItem(COMPRESSED_COBBLESTONE5, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_COBBLESTONE6 = new CompressedCobblestone(FabricBlockSettings.of(Material.STONE).strength(12, 100000).breakByTool(FabricToolTags.PICKAXES, 0).build());
	private static final Item COMPRESSED_COBBLESTONE6_ITEM = new BlockItem(COMPRESSED_COBBLESTONE6, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_COBBLESTONE7 = new CompressedCobblestone(FabricBlockSettings.of(Material.STONE).strength(16, 18000000).breakByTool(FabricToolTags.PICKAXES, 0).build());
	private static final Item COMPRESSED_COBBLESTONE7_ITEM = new BlockItem(COMPRESSED_COBBLESTONE7, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_COBBLESTONE8 = new CompressedCobblestone(FabricBlockSettings.of(Material.STONE).strength(20, 18000000).breakByTool(FabricToolTags.PICKAXES, 0).build());
	private static final Item COMPRESSED_COBBLESTONE8_ITEM = new BlockItem(COMPRESSED_COBBLESTONE8, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_DIRT = new CompressedDirt(FabricBlockSettings.of(Material.EARTH).strength(2, 40).breakByTool(FabricToolTags.SHOVELS, 0).breakByTool(FabricToolTags.PICKAXES, 0).build());
	private static final Item COMPRESSED_DIRT_ITEM = new BlockItem(COMPRESSED_DIRT, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_DIRT2 = new CompressedDirt(FabricBlockSettings.of(Material.EARTH).strength(2, 100).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_DIRT2_ITEM = new BlockItem(COMPRESSED_DIRT2, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_DIRT3 = new CompressedDirt(FabricBlockSettings.of(Material.EARTH).strength(2, 200).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_DIRT3_ITEM = new BlockItem(COMPRESSED_DIRT3, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_DIRT4 = new CompressedDirt(FabricBlockSettings.of(Material.EARTH).strength(2, 1000).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_DIRT4_ITEM = new BlockItem(COMPRESSED_DIRT4, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_DIRT5 = new CompressedDirt(FabricBlockSettings.of(Material.EARTH).strength(3, 2000).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_DIRT5_ITEM = new BlockItem(COMPRESSED_DIRT5, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_DIRT6 = new CompressedDirt(FabricBlockSettings.of(Material.EARTH).strength(3, 5000).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_DIRT6_ITEM = new BlockItem(COMPRESSED_DIRT6, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_DIRT7 = new CompressedDirt(FabricBlockSettings.of(Material.EARTH).strength(4, 10000).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_DIRT7_ITEM = new BlockItem(COMPRESSED_DIRT7, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_DIRT8 = new CompressedDirt(FabricBlockSettings.of(Material.EARTH).strength(4, 100000).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_DIRT8_ITEM = new BlockItem(COMPRESSED_DIRT8, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_GRAVEL = new CompressedGravel(FabricBlockSettings.of(Material.EARTH).strength(3, 40).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_GRAVEL_ITEM = new BlockItem(COMPRESSED_GRAVEL, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_GRAVEL2 = new CompressedGravel(FabricBlockSettings.of(Material.EARTH).strength(4, 100).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_GRAVEL2_ITEM = new BlockItem(COMPRESSED_GRAVEL2, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_GRAVEL3 = new CompressedGravel(FabricBlockSettings.of(Material.EARTH).strength(6, 150).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_GRAVEL3_ITEM = new BlockItem(COMPRESSED_GRAVEL3, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_GRAVEL4 = new CompressedGravel(FabricBlockSettings.of(Material.EARTH).strength(8, 200).breakByTool(FabricToolTags.SHOVELS, 1).build());
	private static final Item COMPRESSED_GRAVEL4_ITEM = new BlockItem(COMPRESSED_GRAVEL4, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_GRAVEL5 = new CompressedGravel(FabricBlockSettings.of(Material.EARTH).strength(10, 500).breakByTool(FabricToolTags.SHOVELS, 1).build());
	private static final Item COMPRESSED_GRAVEL5_ITEM = new BlockItem(COMPRESSED_GRAVEL5, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_GRAVEL6 = new CompressedGravel(FabricBlockSettings.of(Material.EARTH).strength(12, 1000).breakByTool(FabricToolTags.SHOVELS, 1).build());
	private static final Item COMPRESSED_GRAVEL6_ITEM = new BlockItem(COMPRESSED_GRAVEL6, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_GRAVEL7 = new CompressedGravel(FabricBlockSettings.of(Material.EARTH).strength(16, 10000).breakByTool(FabricToolTags.SHOVELS, 2).build());
	private static final Item COMPRESSED_GRAVEL7_ITEM = new BlockItem(COMPRESSED_GRAVEL7, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_GRAVEL8 = new CompressedGravel(FabricBlockSettings.of(Material.EARTH).strength(20, 100000).build());
	private static final Item COMPRESSED_GRAVEL8_ITEM = new BlockItem(COMPRESSED_GRAVEL8, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_SAND = new CompressedSand(FabricBlockSettings.of(Material.EARTH).strength(2, 40).build());
	private static final Item COMPRESSED_SAND_ITEM = new BlockItem(COMPRESSED_SAND, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_SAND2 = new CompressedSand(FabricBlockSettings.of(Material.EARTH).strength(2, 100).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_SAND2_ITEM = new BlockItem(COMPRESSED_SAND2, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_SAND3 = new CompressedSand(FabricBlockSettings.of(Material.EARTH).strength(2, 200).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_SAND3_ITEM = new BlockItem(COMPRESSED_SAND3, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_SAND4 = new CompressedSand(FabricBlockSettings.of(Material.EARTH).strength(2, 1000).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_SAND4_ITEM = new BlockItem(COMPRESSED_SAND4, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_SAND5 = new CompressedSand(FabricBlockSettings.of(Material.EARTH).strength(3, 2000).breakByTool(FabricToolTags.SHOVELS, 0).build());
	private static final Item COMPRESSED_SAND5_ITEM = new BlockItem(COMPRESSED_SAND5, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_SAND6 = new CompressedSand(FabricBlockSettings.of(Material.EARTH).strength(3, 5000).breakByTool(FabricToolTags.SHOVELS, 1).build());
	private static final Item COMPRESSED_SAND6_ITEM = new BlockItem(COMPRESSED_SAND6, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_SAND7 = new CompressedSand(FabricBlockSettings.of(Material.EARTH).strength(4, 10000).breakByTool(FabricToolTags.SHOVELS, 1).build());
	private static final Item COMPRESSED_SAND7_ITEM = new BlockItem(COMPRESSED_SAND7, new Item.Settings().group(ItemGroup.MATERIALS));
	private static final Block COMPRESSED_SAND8 = new CompressedSand(FabricBlockSettings.of(Material.EARTH).strength(4, 100000).breakByTool(FabricToolTags.SHOVELS, 2).build());
	private static final Item COMPRESSED_SAND8_ITEM = new BlockItem(COMPRESSED_SAND8, new Item.Settings().group(ItemGroup.MATERIALS));

	@Override
	public void onInitialize() {
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_cobblestone_x1"), COMPRESSED_COBBLESTONE);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_cobblestone_x1"), COMPRESSED_COBBLESTONE_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_cobblestone_x2"), COMPRESSED_COBBLESTONE2);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_cobblestone_x2"), COMPRESSED_COBBLESTONE2_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_cobblestone_x3"), COMPRESSED_COBBLESTONE3);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_cobblestone_x3"), COMPRESSED_COBBLESTONE3_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_cobblestone_x4"), COMPRESSED_COBBLESTONE4);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_cobblestone_x4"), COMPRESSED_COBBLESTONE4_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_cobblestone_x5"), COMPRESSED_COBBLESTONE5);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_cobblestone_x5"), COMPRESSED_COBBLESTONE5_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_cobblestone_x6"), COMPRESSED_COBBLESTONE6);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_cobblestone_x6"), COMPRESSED_COBBLESTONE6_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_cobblestone_x7"), COMPRESSED_COBBLESTONE7);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_cobblestone_x7"), COMPRESSED_COBBLESTONE7_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_cobblestone_x8"), COMPRESSED_COBBLESTONE8);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_cobblestone_x8"), COMPRESSED_COBBLESTONE8_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_dirt_x1"), COMPRESSED_DIRT);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_dirt_x1"), COMPRESSED_DIRT_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_dirt_x2"), COMPRESSED_DIRT2);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_dirt_x2"), COMPRESSED_DIRT2_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_dirt_x3"), COMPRESSED_DIRT3);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_dirt_x3"), COMPRESSED_DIRT3_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_dirt_x4"), COMPRESSED_DIRT4);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_dirt_x4"), COMPRESSED_DIRT4_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_dirt_x5"), COMPRESSED_DIRT5);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_dirt_x5"), COMPRESSED_DIRT5_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_dirt_x6"), COMPRESSED_DIRT6);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_dirt_x6"), COMPRESSED_DIRT6_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_dirt_x7"), COMPRESSED_DIRT7);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_dirt_x7"), COMPRESSED_DIRT7_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_dirt_x8"), COMPRESSED_DIRT8);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_dirt_x8"), COMPRESSED_DIRT8_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_gravel_x1"), COMPRESSED_GRAVEL);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_gravel_x1"), COMPRESSED_GRAVEL_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_gravel_x2"), COMPRESSED_GRAVEL2);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_gravel_x2"), COMPRESSED_GRAVEL2_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_gravel_x3"), COMPRESSED_GRAVEL3);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_gravel_x3"), COMPRESSED_GRAVEL3_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_gravel_x4"), COMPRESSED_GRAVEL4);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_gravel_x4"), COMPRESSED_GRAVEL4_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_gravel_x5"), COMPRESSED_GRAVEL5);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_gravel_x5"), COMPRESSED_GRAVEL5_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_gravel_x6"), COMPRESSED_GRAVEL6);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_gravel_x6"), COMPRESSED_GRAVEL6_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_gravel_x7"), COMPRESSED_GRAVEL7);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_gravel_x7"), COMPRESSED_GRAVEL7_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_gravel_x8"), COMPRESSED_GRAVEL8);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_gravel_x8"), COMPRESSED_GRAVEL8_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_sand_x1"), COMPRESSED_SAND);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_sand_x1"), COMPRESSED_SAND_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_sand_x2"), COMPRESSED_SAND2);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_sand_x2"), COMPRESSED_SAND2_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_sand_x3"), COMPRESSED_SAND3);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_sand_x3"), COMPRESSED_SAND3_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_sand_x4"), COMPRESSED_SAND4);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_sand_x4"), COMPRESSED_SAND4_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_sand_x5"), COMPRESSED_SAND5);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_sand_x5"), COMPRESSED_SAND5_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_sand_x6"), COMPRESSED_SAND6);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_sand_x6"), COMPRESSED_SAND6_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_sand_x7"), COMPRESSED_SAND7);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_sand_x7"), COMPRESSED_SAND7_ITEM);
		Registry.register(Registry.BLOCK, new Identifier("compressedblocks", "compressed_sand_x8"), COMPRESSED_SAND8);
		Registry.register(Registry.ITEM, new Identifier("compressedblocks", "compressed_sand_x8"), COMPRESSED_SAND8_ITEM);


	}
}
